<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Autofac" Version="8.3.0" />
    <PackageVersion Include="Autofac.Extensions.DependencyInjection" Version="10.0.0" />
	<PackageVersion Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.2" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="9.0.1" />
  </ItemGroup>
</Project>