<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>bdd5afd9-3633-4e80-8231-6040301a27f4</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\dafukMedia.Service\dafukMedia.Service.csproj" />
    <ProjectReference Include="..\dafukMedia.DTO\dafukMedia.DTO.csproj" />
    <ProjectReference Include="..\dafukMedia.Model\dafukMedia.Data.csproj" />
  </ItemGroup>

</Project>
